Request new match
Contraversum/ContraBot pull request #74
Opened 2023-10-15 19:03 UTC by q-Sci

2023-10-17 12:38 UTC, GregTCLTK commented on questions.ts
> +const questions = [
ig we could just store the questions in a questions.json file

2023-10-17 12:38 UTC, GregTCLTK commented
this pr is kinda critical as it probably breaks all other open and future prs due to massive merge conflicts

2023-10-18 10:56 UTC, johan-t commented
> this pr is kinda critical as it probably breaks all other open and future prs due to massive merge conflicts

I agree, I think we should first merge #71 and then merge this one

2023-10-18 10:57 UTC, johan-t commented
Can we also merge this directly into main?

2023-10-18 13:29 UTC, q-Sci commented
> Can we also merge this directly into main?

Yes we can. But what happened to the concept of the pre-production branch?

2023-10-21 09:38 UTC, johan-t commented
> > Can we also merge this directly into main?
> 
> Yes we can. But what happened to the concept of the pre-production branch?

As long as this branch is a branch of the development branch it is fine, we just need to remember to merge main into development before starting something new

2023-10-21 09:57 UTC, johan-t reviewed
General Notes: 
- I am not getting a new match, only the one I have been matched with before

2023-10-21 10:03 UTC, johan-t requested changes

2023-10-21 10:03 UTC, johan-t commented on commands/match/match-command.ts
> +            content: 'Bitte beantworte den Meinungstest vollständig, bevor du mit Anderen gematcht werden kannst! Bitte nutze dazu den Befehl `/test`.',
Could we maybe automatically trigger the test command if the user has not finished the test?

2023-10-21 10:05 UTC, johan-t commented
Also could you think of a way where we could put a button that starts the /match command to make it easier for users to find this feature?

2023-10-22 23:15 UTC, merged

2023-10-22 23:16 UTC, GregTCLTK commented
please don't use feature branches to completely re-structure the entire codebase in the future